Module7 task2
htmlacademy-ecmascript/375607-cinemaddict-14 pull request #13
Opened 2021-05-18 19:16 UTC by olga028383

Привет. У меня по заданию есть вопрос - не могу понять что должно выводиться в Top genre  в окне статистики.
И у меня неправильно считает время в статистике days.js - как это можно поправить? Вернее длину в минутах мой метод считает верно. а dayjs при форматировании косяит,  метод createTimeLength, файл \src\view\stats.js

2021-05-19 11:55 UTC, Shv-sergey70 commented
__не могу понять что должно выводиться в Top genre в окне статистики.__
Один жанр, который принадлежит к большему количеству фильмов

2021-05-19 12:19 UTC, Shv-sergey70 commented
__Вернее длину в минутах мой метод считает верно. а dayjs при форматировании косяит, метод createTimeLength, файл \src\view\stats.js__
Ты все верно пишешь. Просто dayjs переводит остальное в дни, а мы их не показываем. Здесь будет проще вручную поделить минуты, для определения часов и остатка минут

2021-05-19 12:22 UTC, Shv-sergey70 requested changes

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/view/stats.js
> +  return filmGenres;
Всю эту логику можно поместить в один `reduce`

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/view/stats.js
> +  const statisticElement = element;
Это действие бесполезно. `statisticElement === element` - даст true, поэтому можешь параметр сразу назвать `statisticElement`, вместо `element`

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/view/stats.js
> +  constructor(films, activeFilter) {
А тут нужны все фильмы? Может просто можно сразу передавать просмотренные фильмы?

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/utils/stats.js
> +  return films.reduce((previousValue, currentValue) => {
Обычно первый аккумулятор называется `accumulator` или похожим образом, но это точно не `previousValue`. Там сумма всех предыдущих значений

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/utils/stats.js
> +    return +previousValue + currentValue.runTime;
Перед `previousValue` `+` не нужен

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/view/stats.js
> +const createTimeLength = (films) => films.length > 0 ? `${getTime(countTimeLengthWatch(films), 'H[<span class="statistic__item-description">h</span>] mm[<span class="statistic__item-description">m</s
В данном случае использование тернарного оператора не делает код понятнее. Поэтому стоит воспользоваться полной версией:
```
const createTimeLength = (films) => {
  if (films.length === 0) {
    return 0;
  }

  return `${getTime(countTimeLengthWatch(films), 'H[<span class="statistic__item-description">h</span>] mm[<span class="statistic__item-description">m</span>]')}`;
};
```

2021-05-19 12:22 UTC, Shv-sergey70 commented on src/view/stats.js
> +  });
Такое решение не подходит. Ты делаешь очень много циклов, из-за вложенности. Попробуй сделать все в рамках одного reduce

2021-05-21 19:21 UTC, olga028383 commented on src/view/stats.js
> +  constructor(films, activeFilter) {
А тут я и передаю только просмотренные, просто переменная наз. так

2021-05-22 07:25 UTC, Shv-sergey70 requested changes
При каждом переключении со статистики на фильтр по `favorites` и тд - появляется дополнительная статистика по фильмам в футере
![image](https://user-images.githubusercontent.com/35741647/119218218-f543b900-bae7-11eb-89b4-006077e2397f.png)

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/api/api.js
> +  }
Вряд ли этот метод будет нормально работать. Ты используешь в нем `this`, а статические методы не имеют доступа к контексту экземпляра класса. Они работают на уровне класса

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/model/films.js
> +  sortRating() {
`getSortedByRating` так нагляднее

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/model/films.js
> +      return b.rating - a.rating;
Можно написать так:
```
return this._films.slice().sort((a, b) => b.rating - a.rating);
```

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/model/films.js
> +  sortComment() {
Тут то же что и выше для рейтинга

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/presenter/comments.js
> +    getConnect().getComments(this._film.id)
`getConnect` - это добавляет в класс немного магии. В целом так можно сделать, но нагляднее, если эта зависимость, в виде API будет передана в виде параметра конструктора

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/presenter/film.js
> +    this._commentsPresenter = new CommentsPresenter(container, this._updateFilmHandler, this._closeModalEscKeydownHandler, this._filmModel);
А зачем передавать модель фильма в презентер комментов? Походе что там она не используется

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/menu/menu.js
> +const MenuTemplate = () => {
Переменная/функция не должна называться с большой буквы

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/menu/menu.js
> +  return '<nav class="main-navigation"></nav>';
Всю эту разметку можно поместить в метод `getTemplate`. Нет смысла в отдельной функции

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/menu/stats-item.js
> +  return ' <a href="#stats" class="main-navigation__additional">Stats</a>';
Это тоже можно поместить в `getTemplate`

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/menu/stats-item.js
> +  constructor(){
Между круглыми и фигурными скобками метода нужен отступ в 1 пробел

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/rank-user.js
> +    this._films = films;
А зачем это свойство, если фильмы нужны только чтобы посчитать ранг?

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/rank-user.js
> +    this._rankName = getRankUser(films);
Было бы лучше, если бы компонент сам не занимался вычислениями ранга, а на вход сразу принимал готовое значение для отрисовки

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/stats.js
> +  const uniqueGenresCount = uniqueGenres.map((genre) => countFilmsByWatched(films, genre));
Тут осталась та же логика. У тебя есть внешний цикл `map`, который, к примеру, запустится 10 раз. В этом цикле есть `countFilmsByWatched`, который внутри содержит цикл `filter`, который запустится, к примеру, еще 10 раз.
Это уже около 100 итераций. 
И чем больше будет элементов, тем больше придется обходов делать в цикле.
Сложность выполнения такой функции O(N^2). Что довольно тяжело. Можно и нужно сделать линейную сложность O(N).

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/stats.js
> +  const uniqueGenresCount = uniqueGenres.map((genre) => countFilmsByWatched(films, genre));
Если не будет понятно как именно это организовать - пиши в ЛС, подскажу

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/stats.js
> +    accumulator[genre] = (accumulator[genre] || 0) + 1;
👍

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/stats.js
> +  constructor(films, activeFilter) {
Давай тогда так и назовем, `watchedFilms`

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/view/stats.js
> +const renderChart = (films, element) => {
Давай еще отсортируем вывод жанров с количеством, как на картинке в задании
![image](https://user-images.githubusercontent.com/35741647/119218185-c0376680-bae7-11eb-9837-e55d756040ae.png)

2021-05-22 07:25 UTC, Shv-sergey70 commented on src/utils/stats.js
> +  const minTime = 60;
Это можно сделать константой и вынести за пределы функции

2021-05-22 08:50 UTC, olga028383 commented on src/view/stats.js
> +  const uniqueGenresCount = uniqueGenres.map((genre) => countFilmsByWatched(films, genre));
переписала, сразу как-то не дошло

2021-05-22 09:24 UTC, olga028383 commented on src/presenter/comments.js
> +    getConnect().getComments(this._film.id)
Я в апи не удалила статичный метод и ты был прав, он не возвращает объект через this. getConnect я сделала как утилитарную функцию, потому что требуется соединение в нескольких местах. Не хотелось пробрасывать апи через параметры в презенторы, там во все 3 нужно было бы по цепочке Так норм оставить или лучше все-таки пробросить чтобы было одно создание объекта ? https://github.com/olga028383/375607-cinemaddict-14/blob/module7-task2/src/utils/api.js

2021-05-22 19:30 UTC, Shv-sergey70 commented on src/presenter/comments.js
> +    getConnect().getComments(this._film.id)
если говорить с точки зрения чистого кода - то да, лучше через параметр конструктора внедрить зависимость. Но в целом, если сделаешь так как у тебя - это не будет критично в рамках проекта

2021-05-22 19:35 UTC, merged