Rendered the template list
htmlacademy-ecmascript/375607-cinemaddict-14 pull request #3
Opened 2021-03-31 19:32 UTC by olga028383

2021-04-01 08:29 UTC, Shv-sergey70 requested changes

2021-04-01 08:29 UTC, Shv-sergey70 commented on src/main.js
> +const list = document.createElement('section');
Лучше обойтись без ручного создания дом-элементов. Если нужна секция с определенным классом - то это может быть небольшой компонент

2021-04-01 08:29 UTC, Shv-sergey70 commented on src/view/card.js
> +};
Этой логики тут быть не должно. Компонент `card` должен содержать только разметку и внутреннюю логику. А какое количество нужно отрисовать -  это забота уже `main.js`

2021-04-01 08:29 UTC, Shv-sergey70 commented on src/view/films-list.js
> +      <h2 class="films-list__title visually-hidden">${title}</h2>
А зачем эта переменная? Почему просто не вставить текст вместо нее

2021-04-02 19:54 UTC, olga028383 commented on src/main.js
> +const list = document.createElement('section');
поняла

2021-04-02 19:54 UTC, olga028383 commented on src/view/card.js
> +};
суть тоже ясна

2021-04-02 19:55 UTC, olga028383 commented on src/view/films-list.js
> +      <h2 class="films-list__title visually-hidden">${title}</h2>
Тут просто хотелось вынести текст из разметки. Ок , поправлю

2021-04-04 18:53 UTC, Shv-sergey70 commented on src/main.js
> +const COUNT_CARD_TOP = 2;
Тут стоит использовать перечисление

2021-04-04 18:53 UTC, merged