Added test data
htmlacademy-ecmascript/375607-cinemaddict-14 pull request #4
Opened 2021-04-10 11:51 UTC by olga028383

Чего-то я не поняла в какой момент мне открывать окно. Пока что сделала таким способом, но может можно было как-то иначе, проще. Не реализовывала закрытие еще

2021-04-12 16:53 UTC, Shv-sergey70 requested changes

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/constants.js
> +const Emotions = [
Константа должна быть полностью в верхнем регистре

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/lib.js
> +};
В обеих функциях можно использовать короткий синтаксис стрелочных функций без `return`

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/main.js
> +const cards = new Array(COUNT_CARD_All).fill().map(() => generateCard());
По документации метод `fill` должен принимать параметром значение. Так что можно передать пустую строку или null

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/main.js
> +footer.innerHTML = `${cards.length.toLocaleString()} movies inside`;
Это бы в компонент завернуть, чтобы не делать `innerHTML`

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +const Names = [
Эту и переменные ниже нужно оформить как константы

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +  return {
Можно коротким синтаксисом без `return`

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +    name: Names[getRandom(0, Names.length - 1)],
`Names[getRandom(0, Names.length - 1)]` - подобная логика описана во многих местах - нужно создать функцию

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +    ageRating: getRandom(0, 20),
Цифры в константы или перечисление

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +    length: getRandom(60, 210),
Хм, давай подберем более подходящее название

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/card.js
> +    isWatchList: Boolean(getRandom(0, 1)),
`Boolean(getRandom(0, 1))` - дублируется 3 раза - это бы в функцию

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/comment.js
> +const Texts = [
Константы

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/comment.js
> +    id: ++count,
Хм, ручное создание id. Может воспользуешься мини-библиотекой `nanoid`?

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/comment.js
> +    date: new Date(getRandom(2000, 2020), getRandom(0, 13)),
Цифры в перечисление

2021-04-12 16:53 UTC, Shv-sergey70 commented on src/mock/filter.js
> +    return {
Можно без return, используя короткий синтаксис стрелочных функций

2021-04-13 17:08 UTC, olga028383 commented on src/main.js
> +footer.innerHTML = `${cards.length.toLocaleString()} movies inside`;
А здесь в шаблоне уж есть дом элемент http://prntscr.com/11c9mwb  его удалить ив ставить компонентом? Или можно добавить данные как textContent

2021-04-14 12:51 UTC, Shv-sergey70 commented on src/lib.js
> +const nanoid = require('nanoid');
Почему `require`, а не обычный импорт?

2021-04-14 12:51 UTC, Shv-sergey70 commented on src/main.js
> +footer.innerHTML = `${cards.length.toLocaleString()} movies inside`;
Да, можно сделать компонент, удалив из разметки эту часть

2021-04-14 12:51 UTC, Shv-sergey70 commented on src/mock/card.js
> +const isActiveButton = () => Boolean(getRandom(0, 1));
Это скорее `getRandomBoolean`

2021-04-14 12:51 UTC, Shv-sergey70 commented on src/mock/comment.js
> +  return {
Можно коротким синтаксисом без `return`

2021-04-14 12:51 UTC, merged