Module3 task1
htmlacademy-ecmascript/375607-cinemaddict-14 pull request #5
Opened 2021-04-14 18:09 UTC by olga028383

2021-04-16 19:29 UTC, olga028383 commented
Все таки я раздробила все намелкие компоненты, потому что со 2 способом возникла снова проблема, чтобы повесить обработчик постребовалось бы искать элементы

2021-04-17 20:49 UTC, Shv-sergey70 requested changes
Если открыть попап, закрыть его через крестик, а потом нажимать `Esc`, будут ошибки в консоли. Нужно поправить - это утечка

2021-04-17 20:49 UTC, Shv-sergey70 commented on src/main.js
> +  comment.addEventListener('click', openModalHandler);
Элементы лучше найти через `querySelectorAll` и в цикле добавить обработчики

2021-04-17 20:49 UTC, Shv-sergey70 commented on src/main.js
> +  const COUNT_CARD_LIST = 5;
Это должно быть за пределами функций

2021-04-19 17:03 UTC, merged